repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.12
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pytest-dev/pytest
    rev: 7.4.2
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest tests
        language: python
        pass_filenames: false
        always_run: true